const express = require('express');
const mongoose = require('mongoose');
const bodyParser = require('body-parser');
const path = require('path');
require('dotenv').config();

const events = require('./routes/api/events');
const prerecordedevents = require('./routes/api/prerecordedevents');



const app = express();

//bodyparser
app.use(bodyParser.json());

//DB config
console.log(process.env.DATABASE);
const db = require('./config/keys').mongoURI;


// Connect to Mongo

mongoose
    .connect(db, { useNewUrlParser: true, useUnifiedTopology: true })
    .then(() => console.log('Connected to Database'))
    .catch(err => {
        console.log(err)
        console.log("Could not connect to database")
    });

//Use Routes
app.use('/api/events/live', events);
app.use('/api/events/recorded', prerecordedevents);

//Served compiled static React content in production
if (process.env.NODE_ENV === 'production') {
    //serve static files generated by React
    app.use(express.static('frontend/build'));

    app.get('*', (req, res) => {
        res.sendFile(path.resolve(__dirname, 'frontend', 'build', 'index.html'));
    });
}

const port = process.env.PORT || 5000;

app.listen(port, () => console.log(`Server started on port ${port}`));